// Re-export everything from the canonical lib/api.js
// Some components import from "../lib/api" (app-relative) so this bridges them.
export {
  apiClient,
  fetchProducts,
  fetchCompleteWheelProducts,
  fetchRimProducts,
  fetchTyresExport,
  fetchExtraProducts,
  fetchProduct,
  fetchBrands,
  createOrder,
  fetchOrder,
  listOrders,
  fetchStockExport,
  fetchStockLocations,
  fetchVehicleByPlate,
  fetchGarages,
  fetchTyrehotelsByPlate,
  fetchTyrehotelDetail,
  parseDimension,
  formatPrice,
  oreToSek,
  seasonLabel,
  seasonBadgeClass,
  buildEontyreImageUrl,
  productImageUrl,
  normaliseProductsResponse,
} from "@/lib/api";
